FROM node:lts-slim

WORKDIR /root
COPY ./application_default_credentials.json .

RUN mkdir api

WORKDIR /root/api

COPY ./dist/package.json .
COPY ./dist/pnpm-lock.yaml .

RUN corepack enable pnpm
RUN pnpm i

COPY ./dist/ .

WORKDIR /root

CMD [ "node", "api" ]
